### ISSUE TITLE
Your API Key is Visible

### ISSUE THREAD

**Issue by pmichaeljones** [erabug/thesaurus-rex#1]
Super cool web app! I built a CrossFit Name Generator using the same API. However, your API key is visible in your source code. Someone might steal it and use it in their app and charge YOUR account. Just a heads up.

**Comment by erabug** [comment]
Hey, thanks for checking out my app! And thanks for the heads up about the API key. I know it's a bit of a gaffe to have it exposed on GitHub. However, since it's just a demo project and since the key is only used by the API provider for analytics, I don't believe there's an incentive for someone to take it.

**Comment by pmichaeljones** [comment]
True. I think you need to hit like 10,000/hits per day and then they ask for your billing details. Regardless, great app!
